{
 "title": "Razer AIKit Dashboard",
 "time": { "from": "now-1m", "to": "now" },
 "refresh": "1s",
 "panels": [
  {
   "type": "canvas",
   "gridPos": { "h": 3, "w": 24, "x": 0, "y": 0 },
   "targets": [
    {}
   ]
  },
  {
   "title": "Total GPU Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "ray_node_gram_available + ray_node_gram_used",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Used GPU Memory",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 6, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "mbytes" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "ray_node_gram_used", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Output Token Throughput",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 12, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "tok/s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "rate(vllm:generation_tokens_total[$__rate_interval])",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "Time to First Token (TTFT)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 16, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_to_first_token_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Inter-Token Latency (ITL)",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "s" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum by(le) (rate(vllm:time_per_output_token_seconds_bucket[$__rate_interval])))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GPU Utilisation",
   "type": "gauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  label_replace(\r\n    ray_node_gpus_utilization,\r\n    \"GpuDeviceName\",\r\n    \"$1\",\r\n    \"GpuDeviceName\",\r\n    \"^[ ]*NVIDIA[ ]*(.*)$\"\r\n  ),\r\n  \"GpuDeviceName\",\r\n  \"$1\",\r\n  \"GpuDeviceName\",\r\n  \"^[ ]*GeForce[ ]*(.*)$\"\r\n)\r\n",
     "legendFormat": "{{GpuDeviceName}}"
    }
   ]
  },
  {
   "title": "Output Token Throughput",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "expr": "rate(vllm:generation_tokens_total[$__rate_interval])",
     "legendFormat": "{{model_name}}"
    }
   ]
  },
  {
   "title": "GPU Memory Usage",
   "type": "bargauge",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "label_replace(\r\n  label_replace(\r\n    ray_node_gram_used / (ray_node_gram_used + ray_node_gram_available),\r\n    \"GpuDeviceName\",\r\n    \"$1\",\r\n    \"GpuDeviceName\",\r\n    \"^[ ]*NVIDIA[ ]*(.*)$\"\r\n  ),\r\n  \"GpuDeviceName\",\r\n  \"$1\",\r\n  \"GpuDeviceName\",\r\n  \"^[ ]*GeForce[ ]*(.*)$\"\r\n)\r\n",
     "legendFormat": "{{ip}} | {{GpuDeviceName}}"
    }
   ]
  },
  {
   "title": "Request Load",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "targets": [
    {
     "expr": "rate(vllm:request_success_total[$__rate_interval])",
     "legendFormat": "{{finished_reason}}"
    }
   ]
  }
 ]
}