#!/bin/bash

# restore LIBRARY_PATH
export LIBRARY_PATH=$CONDA_BASE_LIBRARY_PATH

# restore LD_LIBRARY_PATH
export LD_LIBRARY_PATH=$CONDA_BASE_LD_LIBRARY_PATH

# restore PATH
export PATH=$CONDA_BASE_PATH
