[tool.poetry]
name = "rzr"
version = "0.3.1"
description = "A package for Razer GPU compute and AI services"
authors = ["Razer Inc."]
license = "Apache-2.0"
packages = [
    { include = "src" },
    { include = "util" }
]

[tool.poetry.dependencies]
python = "~3.12" # vllm wants this stricter constraint
typer = ">0.19.2"
numpy = "^2.1.2"
psutil = "^7.0.0"
transformers = "^4.51.3"
accelerate = "^1.7.0"
nvidia-ml-py = ">12.575.51"
prometheus-client = ">0.22.1"
typing-extensions = "^4.14.1"
openai = ">1.97.1"
humanize = "^4.14.0"


[tool.poetry.group.dev.dependencies]
pytest = "^8.3.4"
pytest-mock = "^3.14.1"

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"

[tool.poetry.plugins."console_scripts"]
rzr-aikit = "src.cli:app"
run_vllm = "util.run_vllm:main"
